-- =====================
-- USERS
-- =====================
CREATE TABLE IF NOT EXISTS "users" (
    "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "full_name" varchar(255) NOT NULL,
    "username" varchar(255) NOT NULL,
    "email" varchar(255) NOT NULL,
    "verified" boolean DEFAULT false,
    "email_verified" boolean DEFAULT false,
    "password" varchar(255) NOT NULL,
    "password_length" smallint DEFAULT 0 NOT NULL,
    "profile_url" varchar(255) DEFAULT 'profile-icon-default.png' NOT NULL,
    "role_id" smallint DEFAULT 0 NOT NULL,
    "security_code" text,
    "ban_reason" text,
    "followers" integer DEFAULT 0,
    "following" integer DEFAULT 0,
    "banned_until" timestamp,
    "created_at" timestamptz DEFAULT now(),
    "updated_at" timestamptz DEFAULT now(),
    CONSTRAINT "users_username_unique" UNIQUE("username"),
    CONSTRAINT "users_email_unique" UNIQUE("email")
);

-- =====================
-- POSTS
-- =====================
CREATE TABLE IF NOT EXISTS "posts" (
    "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "owner_id" bigint,
    "description" text,
    "image_url" text,
    "like_count" integer DEFAULT 0,
    "comment_count" integer DEFAULT 0,
    "created_at" timestamptz DEFAULT now(),
    CONSTRAINT "posts_owner_id_users_id_fk"
        FOREIGN KEY ("owner_id")
        REFERENCES "users"("id")
        ON DELETE NO ACTION ON UPDATE NO ACTION
);

-- =====================
-- POST LIKES
-- =====================
CREATE TABLE IF NOT EXISTS "post_likes" (
    "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "post_id" bigint NOT NULL,
    "user_id" bigint NOT NULL,
    "created_at" timestamptz DEFAULT now(),
    CONSTRAINT "post_likes_post_id_posts_id_fk"
        FOREIGN KEY ("post_id")
        REFERENCES "posts"("id")
        ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT "post_likes_user_id_users_id_fk"
        FOREIGN KEY ("user_id")
        REFERENCES "users"("id")
        ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT "post_likes_unique" UNIQUE("post_id", "user_id")
);

-- =====================
-- POST COMMENTS
-- =====================

CREATE TABLE IF NOT EXISTS "post_comments" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	"post_id" bigint NOT NULL,
	"user_id" bigint NOT NULL,
    "parent_id" bigint NOT NULL,
	"comment" text NOT NULL,
    "like_count" integer DEFAULT 0,
    "reply_count" integer DEFAULT 0,
	"created_at" timestamp with time zone DEFAULT now(),
    CONSTRAINT "post_comments_post_id_posts_id_fk" 
        FOREIGN KEY ("post_id") 
        REFERENCES "public"."posts"("id") 
        ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT "post_comments_user_id_users_id_fk" 
        FOREIGN KEY ("user_id") 
        REFERENCES "public"."users"("id") 
        ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT "post_comments_parent_id_post_comments_id_fk" 
        FOREIGN KEY ("parent_id") 
        REFERENCES "public"."post_comments"("id") 
        ON DELETE CASCADE ON UPDATE NO ACTION
);

-- =====================
-- POST COMMENT LIKES
-- =====================

CREATE TABLE IF NOT EXISTS "post_comment_likes" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	"post_id" bigint NOT NULL,
    "user_id" bigint NOT NULL,
	"comment_id" bigint NOT NULL,
	"like_count" integer DEFAULT 0,
	"created_at" timestamp with time zone DEFAULT now(),
    CONSTRAINT "post_comment_likes_post_id_posts_id_fk" 
        FOREIGN KEY ("post_id") 
        REFERENCES "public"."posts"("id") 
        ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT "post_comment_likes_comment_id_post_comments_id_fk" 
        FOREIGN KEY ("comment_id") 
        REFERENCES "public"."post_comments"("id") 
        ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT "post_comment_likes_unique" UNIQUE("post_id", "comment_id");
);

-- =====================
-- FOLLOWING LOGS
-- =====================
CREATE TABLE IF NOT EXISTS "following_logs" (
    "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "followed_id" bigint NOT NULL,
    "user_id" bigint NOT NULL,
    "created_at" timestamptz DEFAULT now(),
    CONSTRAINT "following_logs_followed_id_users_id_fk"
        FOREIGN KEY ("followed_id")
        REFERENCES "users"("id")
        ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT "following_logs_user_id_users_id_fk"
        FOREIGN KEY ("user_id")
        REFERENCES "users"("id")
        ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT "following_logs_unique" UNIQUE("user_id", "followed_id")
);

-- =====================
-- SERVER TOKEN
-- =====================
CREATE TABLE IF NOT EXISTS "server_token" (
    "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint NOT NULL,
    "token" text NOT NULL,
    "created_at" timestamptz DEFAULT now(),
	"expires_at" timestamp with time zone NOT NULL,
    CONSTRAINT "server_token_user_id_users_id_fk"
        FOREIGN KEY ("user_id")
        REFERENCES "users"("id")
        ON DELETE CASCADE ON UPDATE NO ACTION
);

-- =====================
-- NOTIFICATIONS
-- =====================
CREATE TABLE IF NOT EXISTS "notifications" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	"recipient_id" bigint NOT NULL,
	"sender_id" bigint NOT NULL,
	"post_id" bigint DEFAULT 0,
    "dev_only" boolean NOT NULL DEFAULT false,
	"comment_id" bigint DEFAULT 0,
	"action" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now(),
    CONSTRAINT "notifications_recipient_id_users_id_fk" 
        FOREIGN KEY ("recipient_id") 
        REFERENCES "public"."users"("id") 
        ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT "notifications_sender_id_users_id_fk" 
        FOREIGN KEY ("sender_id") 
        REFERENCES "public"."users"("id") 
        ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT "notifications_post_id_posts_id_fk" 
        FOREIGN KEY ("post_id") 
        REFERENCES "public"."posts"("id") 
        ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT "notifications_comment_id_post_comments_id_fk" 
        FOREIGN KEY ("comment_id") 
        REFERENCES "public"."post_comments"("id") 
        ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS "reports" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	"user_id" bigint NOT NULL,
	"reporter_id" bigint NOT NULL,
	"post_id" bigint,
	"comment_id" bigint,
    "duration" bigint DEFAULT 0,
    "approved" smallint DEFAULT -1 NOT NULL,
	"reason" text NOT NULL,
    "log_type" text DEFAULT 'Reported' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now(),
    CONSTRAINT "reports_user_id_users_id_fk" 
        FOREIGN KEY ("user_id") 
        REFERENCES "public"."users"("id") 
        ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT "reports_reporter_id_users_id_fk" 
        FOREIGN KEY ("reporter_id") 
        REFERENCES "public"."users"("id") 
        ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT "reports_post_id_posts_id_fk" 
        FOREIGN KEY ("post_id") 
        REFERENCES "public"."posts"("id") 
        ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT "reports_comment_id_post_comments_id_fk" 
        FOREIGN KEY ("comment_id") 
        REFERENCES "public"."post_comments"("id") 
        ON DELETE CASCADE ON UPDATE NO ACTION
);

INSERT INTO public.users (id, full_name, username, email, verified, email_verified, "password", password_length, profile_url, role_id, followers, "following", banned_until, created_at, updated_at, security_code)
VALUES(0, 'system', 'system', 'system@gmail.com', false, false, '$argon2id$v=19$m=65536,t=3,p=4$aqV6gLZKSYp8B/GI0prVkA$9AwQyhFzzowrhiXggAFVYKfsXSTb1tB6aFv3PiMwcAQ', 6, 'profile-icon-default.png', 0, 0, 0, NULL, '2025-09-02 15:09:10.872', '2025-09-02 15:09:10.872', NULL);