-- =====================
-- USERS
-- =====================
CREATE TABLE IF NOT EXISTS "users" (
    "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "full_name" varchar(255) NOT NULL,
    "username" varchar(255) NOT NULL,
    "email" varchar(255) NOT NULL,
    "verified" boolean DEFAULT false,
    "email_verified" boolean DEFAULT false,
    "password" varchar(255) NOT NULL,
    "password_length" smallint DEFAULT 0 NOT NULL,
    "profile_url" varchar(255) DEFAULT 'profile-icon-default.png' NOT NULL,
    "role_id" smallint DEFAULT 0 NOT NULL,
    "security_code" text,
    "followers" integer DEFAULT 0,
    "following" integer DEFAULT 0,
    "created_at" timestamptz DEFAULT now(),
    "updated_at" timestamptz DEFAULT now(),
    CONSTRAINT "users_username_unique" UNIQUE("username"),
    CONSTRAINT "users_email_unique" UNIQUE("email")
);

-- =====================
-- POSTS
-- =====================
CREATE TABLE IF NOT EXISTS "posts" (
    "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "owner_id" bigint,
    "description" text,
    "image_url" text,
    "like_count" integer DEFAULT 0,
    "comment_count" integer DEFAULT 0,
    "created_at" timestamptz DEFAULT now(),
    CONSTRAINT "posts_owner_id_users_id_fk"
        FOREIGN KEY ("owner_id")
        REFERENCES "users"("id")
        ON DELETE NO ACTION ON UPDATE NO ACTION
);

-- =====================
-- POST LIKES
-- =====================
CREATE TABLE IF NOT EXISTS "post_likes" (
    "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "post_id" bigint NOT NULL,
    "user_id" bigint NOT NULL,
    "created_at" timestamptz DEFAULT now(),
    CONSTRAINT "post_likes_post_id_posts_id_fk"
        FOREIGN KEY ("post_id")
        REFERENCES "posts"("id")
        ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT "post_likes_user_id_users_id_fk"
        FOREIGN KEY ("user_id")
        REFERENCES "users"("id")
        ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT "post_likes_unique" UNIQUE("post_id", "user_id")
);

-- =====================
-- FOLLOWING LOGS
-- =====================
CREATE TABLE IF NOT EXISTS "following_logs" (
    "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "followed_id" bigint NOT NULL,
    "user_id" bigint NOT NULL,
    "created_at" timestamptz DEFAULT now(),
    CONSTRAINT "following_logs_followed_id_users_id_fk"
        FOREIGN KEY ("followed_id")
        REFERENCES "users"("id")
        ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT "following_logs_user_id_users_id_fk"
        FOREIGN KEY ("user_id")
        REFERENCES "users"("id")
        ON DELETE CASCADE ON UPDATE NO ACTION,
    CONSTRAINT "following_logs_unique" UNIQUE("user_id", "followed_id")
);

-- =====================
-- SERVER TOKEN
-- =====================
CREATE TABLE IF NOT EXISTS "server_token" (
    "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint NOT NULL,
    "token" text NOT NULL,
    "created_at" timestamptz DEFAULT now(),
	"expires_at" timestamp with time zone NOT NULL,
    CONSTRAINT "server_token_user_id_users_id_fk"
        FOREIGN KEY ("user_id")
        REFERENCES "users"("id")
        ON DELETE CASCADE ON UPDATE NO ACTION
);